#!/bin/sh

logfile=log.txt

mpg123_info() {
    [ "${str:0:1}" == "@" ] || return
    case "${str:1:1}" in
        "I")  #get only stream title, remove any newlines first
            str="$(echo $str | grep "StreamTitle" | sed "s:.*StreamTitle='::" | sed "s:'.*::")"
            [ "$str" ] && str="@ $str"
        ;;
        "P")
            [ "${str:3:1}" == "0" ] && str="@ stopped"
            [ "${str:3:1}" == "1" ] && str="@ paused"
            [ "${str:3:1}" == "2" ] && str="@ play"
        ;;
        *)
            unset str
        ;;
    esac
}

while [ 1 -eq 1 ]; do
    read str <logfifo
    [ "$str" == "QUITQUIT" ] && break
    dat="$(date +%Y-%m-%d)"
    tim="$(date +%H:%M:%S)"
    mpg123_info
    [ "$str" ] || continue
    echo "[ $dat $tim ] $str" >> "$logfile"
done

#>$logfile
#let mp3 delete logfile if needed

